import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import layoutstyle from "./layout.module.scss";
import Header from "./Components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={layoutstyle.container}>
          <div className={layoutstyle.sideBar}>
            <aside>
              <Sidebar />
            </aside>
          </div>
          <div className={layoutstyle.content}>
            <aside className={layoutstyle.header}>
              <Header />
            </aside>
            <main className={layoutstyle.main}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
